#!/usr/local/bin/bash
## #############################################################
## script to copy new version to the www-readable section
## 
## Synopsis:
##
## #############################################################
## @FILE:    publish
## @PLACE:   Linux Homestation
## @FORMAT:  plain text
## @AUTHOR:  M. Oliver M'o'ller     <omoeller@brics.dk>
## @BEGUN:   Wed Nov 29 10:18:34 2000
## @VERSION: Sun Jul 14 23:30:35 2002
## #############################################################
## 
## ----------------------------------------
echo "** Copying to relevant locations..."
WWW_BASE=$HOME/Domain/Upload
## -- ordinary copies -------------------------------------------
pushd Public;
cp ../Crypter.java .
javac Crypter.java;
cp Base64Handler.class $WWW_BASE/applets/
cp CONST.class $WWW_BASE/applets/
cp Crypter.class $WWW_BASE/applets/
cp CryptoModule.class $WWW_BASE/applets/
cp HashFunction.class $WWW_BASE/applets/
cp Listener.class $WWW_BASE/applets/
cp PublicKey.class $WWW_BASE/applets/
##cp SecretKey.class $WWW_BASE/applets/
chmod 0755 $WWW_BASE/applets/*.class
## -- java source -------------------------------------
cp Crypter.java $WWW_BASE/applets/
cp CryptoModule.java $WWW_BASE/applets/
chmod 0644 $WWW_BASE/applets/Crypt*.java
## ----------------------------------------------------
popd;
## -- millstone copies ------------------------------------------
./makeMillstone;
cp ./.millstone/Base64Handler.class $WWW_BASE/sub/.millstone/
cp ./.millstone/CONST.class $WWW_BASE/sub/.millstone/
cp ./.millstone/HashFunction.class $WWW_BASE/sub/.millstone/
cp ./.millstone/Listener.class $WWW_BASE/sub/.millstone/
cp ./.millstone/MillstoneCrypter.class $WWW_BASE/sub/.millstone/
cp ./.millstone/MillstoneCryptoModule.class $WWW_BASE/sub/.millstone/
cp ./.millstone/PublicKey.class $WWW_BASE/sub/.millstone/
cp ./.millstone/SecretKey.class $WWW_BASE/sub/.millstone/
## -- java source -------------------------------------
cp ./.millstone/MillstoneCrypter.java $WWW_BASE/sub/.millstone/
cp ./.millstone/MillstoneCryptoModule.java $WWW_BASE/sub/.millstone/
##
chmod 0644 $WWW_BASE/sub/.millstone/*.class
chmod 0644 $WWW_BASE/sub/.millstone/MillstoneCrypt*.java
## --------------------------------------------------------------
echo "publish: done."
echo "NOTES:";
echo " + remember to update crypter.html, applet-crypter.html, millstone_crypter.html, applet-millstone_crypter.html"
echo " + remember to update Validate (mkval.bash)";
